## Softmax Classification

In [24]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
x_names = ['SepLength', 'SepWidth', 'PetLength', 'PetWidth']
y_names = ['Prop_Iris-setosa', 'Prop_Iris-versicolor', 'Prop_Iris-virginica']

#### Reads inputs

In [35]:
def inputs(file):
    data = pd.read_table(filepath_or_buffer=file, delimiter=",", header=None, names=x_names + ['Prop'])
    data = pd.get_dummies(data)
    train = data.sample(frac=0.8)
    test = data.drop(train.index)
    return train, test


Train, Test = inputs('data/iris.data.txt')

In [36]:
Train.describe()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>SepLength</th>
      <th>SepWidth</th>
      <th>PetLength</th>
      <th>PetWidth</th>
      <th>Prop_Iris-setosa</th>
      <th>Prop_Iris-versicolor</th>
      <th>Prop_Iris-virginica</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>120.000000</td>
      <td>120.000000</td>
      <td>120.000000</td>
      <td>120.000000</td>
      <td>120.000000</td>
      <td>120.000000</td>
      <td>120.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>5.810000</td>
      <td>3.058333</td>
      <td>3.657500</td>
      <td>1.149167</td>
      <td>0.358333</td>
      <td>0.325000</td>
      <td>0.316667</td>
    </tr>
    <tr>
      <th>std</th>
      <td>0.859196</td>
      <td>0.452553</td>
      <td>1.797555</td>
      <td>0.776655</td>
      <td>0.481521</td>
      <td>0.470339</td>
      <td>0.467127</td>
    </tr>
    <tr>
      <th>min</th>
      <td>4.300000</td>
      <td>2.000000</td>
      <td>1.000000</td>
      <td>0.100000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>5.100000</td>
      <td>2.800000</td>
      <td>1.500000</td>
      <td>0.200000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>5.700000</td>
      <td>3.000000</td>
      <td>4.200000</td>
      <td>1.300000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>6.400000</td>
      <td>3.400000</td>
      <td>5.100000</td>
      <td>1.800000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>7.900000</td>
      <td>4.400000</td>
      <td>6.900000</td>
      <td>2.500000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
    </tr>
  </tbody>
</table>
</div>

In [37]:
Test.describe()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>SepLength</th>
      <th>SepWidth</th>
      <th>PetLength</th>
      <th>PetWidth</th>
      <th>Prop_Iris-setosa</th>
      <th>Prop_Iris-versicolor</th>
      <th>Prop_Iris-virginica</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>30.000000</td>
      <td>30.000000</td>
      <td>30.000000</td>
      <td>30.000000</td>
      <td>30.000000</td>
      <td>30.000000</td>
      <td>30.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>5.976667</td>
      <td>3.036667</td>
      <td>4.163333</td>
      <td>1.396667</td>
      <td>0.233333</td>
      <td>0.366667</td>
      <td>0.400000</td>
    </tr>
    <tr>
      <th>std</th>
      <td>0.686160</td>
      <td>0.353781</td>
      <td>1.588858</td>
      <td>0.683038</td>
      <td>0.430183</td>
      <td>0.490133</td>
      <td>0.498273</td>
    </tr>
    <tr>
      <th>min</th>
      <td>4.800000</td>
      <td>2.400000</td>
      <td>1.300000</td>
      <td>0.100000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>5.425000</td>
      <td>2.825000</td>
      <td>3.775000</td>
      <td>1.050000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>6.050000</td>
      <td>3.000000</td>
      <td>4.650000</td>
      <td>1.500000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>6.475000</td>
      <td>3.200000</td>
      <td>5.250000</td>
      <td>1.800000</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>7.300000</td>
      <td>3.900000</td>
      <td>6.300000</td>
      <td>2.500000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
    </tr>
  </tbody>
</table>
</div>

#### Predicts Y

In [38]:
def inference(x, W, b):
    return tf.nn.softmax(tf.matmul(x, W) + b)

In [39]:
X_train = Train[x_names]
Y_train = Train[y_names]
X_test = Test[x_names]
Y_test = Test[y_names]
x = tf.placeholder(tf.float32, [None, 4])
W = tf.Variable(tf.zeros([4, 3]))
b = tf.Variable(tf.zeros([3]))
predict = inference(x, W, b)
y = tf.placeholder(tf.float32, [None, 3])

#### Crosss Entropy and Accuaracy

In [40]:
crossEntropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=predict))
predictionCorrection = tf.equal(tf.argmax(predict, axis=1), tf.argmax(y, axis=1))
accuracy = tf.reduce_mean(tf.cast(predictionCorrection, tf.float32))

In [43]:
for learningRate in [0.001, 0.01, 0.1, 1.0]:
    optimizer = tf.train.GradientDescentOptimizer(learningRate).minimize(crossEntropy)
    
    with tf.Session() as session:
        tf.global_variables_initializer().run()
        for epoch in range(3):
            session.run(optimizer, feed_dict={x: X_train, y: Y_train})
        acc = session.run(accuracy, feed_dict={x: X_test, y: Y_test})
        print("Learning Rate: ", learningRate)
        print("Accuracy: ", acc)
        session.close()

Learning Rate:  0.001
Accuracy:  0.4
Learning Rate:  0.01
Accuracy:  0.4

Learning Rate:  0.1
Accuracy:  0.4
Learning Rate:  1.0
Accuracy:  0.36666667